version: '3.6'

networks:
  database:
    driver: bridge

volumes:
  database:
    driver: local

services:
  database:
    image: postgres:14.9
    ports:
      - 5432:5432
    networks:
      - database
    volumes:
      - database:/var/lib/postgresql/data
      - ./database/initdb.d:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
