name: PR
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install
      - name: lint
        run: nx affected --target=lint --base=${{github.sha}} --head=main
      - name: format
        run: nx format:check --base=${{github.sha}} --head=main
