name: PR
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install
      - name: lint
        run: npx nx affected --target=lint --base=${{github.sha}} --head= ${{github.event.pull_request.base.sha }} --parallel=3
      - name: format
        run: npx nx format:check --base=${{github.sha}} --head= ${{github.event.pull_request.base.sha }}
      - name: typing
        run: npx nx affected --target=typing --base=${{github.sha}} --head=${{github.event.pull_request.base.sha}} --parallel=3
      - name: test
        run: npx nx affected --target=test --base=${{github.sha}} --head=${{github.event.pull_request.base.sha}} --parallel=3
